Readme.md
Some of the sentences in the README are pretty long and some terms could
do with hyphens. Tidy this up. (v2, addressing comments from original repo)
Signed-off-by: Simon Glass <sjg@chromium.org>
=> Tidy up the README a little

Readme.md
As suggested by https://github.com/CultureHQ/github-actions-badge
=> Link to actions for CI badge

Readme.md
Not sure how I missed this :sweat:
=> Fix CI badge image

Readme.md
@dumblob just need another persons scan over this before merging.
=> Add reviewers guide to readme

nuklear.h, package.json, src/CHANGELOG, src/nuklear_widget.c
Fixes #79
The code deleted here seems to have been an effort to solve what 14dd68e solved so it makes sense that these would conflict. I'm pretty sure 14dd68e is the correct solution though and this was some old hack.
=> Fix bug where padding was subtracted from widget

nuklear.h, src/nuklear_widget.c
Just removing of unused variables
=> nk_widget_fitting() cleanup of unused variables

nuklear.h, package.json, src/CHANGELOG, src/nuklear_tree.c
=> Fix bug where layout was restored incorrectly on tree pop

demo/allegro5/nuklear_allegro5.h
Hello!
This PR adds support for `NK_COMMAND_IMAGE` draw command in allegro5 backend along with two helper functions to create and destroy allegro images stored in `nk_image` struct.
=> Added image support to allegro5 backend

demo/glfw_opengl3/nuklear_glfw_gl3.h
Fix trivial issue causing a build warning
=> fix incorrect memset size in glfw demo shutdown

demo/allegro5/nuklear_allegro5.h
Hello!
This PR adds return value to `nk_allegro5_handle_event`, which now returns boolean (actually integer) indicating whether the event was processed or not. This is similar to other backends; it allows to properly process events in games (i.e. not handle the event in-game if it was handled by Nuklear).
=> Added processed event flag as a return value in allegro5 backend

nuklear.h, package.json, src/CHANGELOG, src/nuklear_property.c
=> Fix nk_property hover bug

demo/glfw_opengl3/nuklear_glfw_gl3.h
=> Fixed copy and paste in glfw_opengl3 demo

nuklear.h, package.json, src/CHANGELOG, src/nuklear_font.c
=> Fix crash when baking merged fonts

nuklear.h, package.json, src/CHANGELOG, src/nuklear.h
Fixes #334
@unsigned-ru can you have a look?
=> Fix "Templates cannot be declared to have 'C' Linkage"

doc/build.sh, doc/nuklear.html
Added a title to the page and removed whitespace from the build script
=> Minor Documentation Changes

.github/workflows/create-tag.yml
Closes: https://github.com/Immediate-Mode-UI/Nuklear/issues/136
Signed-off-by: Aisha Tammy <floss@bsd.ac>
=> create-tag github action for future tags

clib.json, nuklear.h, src/CHANGELOG, src/stb_rect_pack.h, src/stb_truetype.h
Some updates to stb_rect_pack and stb_truetype over from https://github.com/nothings/stb .
=> Update stb_rect_pack and stb_truetype

demo/sdl_renderer/nuklear_sdl_renderer.h
=> Fix incorrect cast on SDL_RenderGeometryRaw()

demo/x11_opengl2/main.c, demo/x11_opengl3/main.c
=> x11: Free XVisualInfo after use

clib.json, nuklear.h, src/CHANGELOG, src/nuklear_text_editor.c
Follow up from https://github.com/Immediate-Mode-UI/Nuklear/pull/480
=> Fix Shift + End in nk_edit

demo/x11/nuklear_xlib.h, demo/x11_xft/nuklear_xlib.h
=> xlib: Fix xlib text drawing background color

demo/x11/nuklear_xlib.h, demo/x11_xft/nuklear_xlib.h
=> xlib backend: implemented arc commands

src/HEADER
=> Add link from the documentation to the code

clib.json, nuklear.h, src/CHANGELOG, src/nuklear_font.c
=> Fix nk_font_bake_pack() using TTC font offset incorrectly

demo/common/overview.c
=> Fix Overview Titlebar Options

nuklear.h, src/nuklear_internal.h
=> Allow disabling STB_*_IMPLEMENTATION

demo/allegro5/nuklear_allegro5.h, demo/d3d11/nuklear_d3d11.h, demo/d3d12/nuklear_d3d12.h, demo/d3d9/nuklear_d3d9.h, demo/gdi/nuklear_gdi.h, demo/gdi_native_nuklear/nuklear_gdi.h, demo/glfw_opengl2/nuklear_glfw_gl2.h, demo/glfw_opengl3/nuklear_glfw_gl3.h, demo/glfw_opengl4/nuklear_glfw_gl4.h, demo/glfw_vulkan/nuklear_glfw_vulkan.h, demo/glfw_vulkan/src/nuklear_glfw_vulkan.in.h, demo/sdl2surface_rawfb/sdl2surface_rawfb.h, demo/sdl_opengl2/nuklear_sdl_gl2.h, demo/sdl_opengl3/nuklear_sdl_gl3.h, demo/sdl_opengles2/nuklear_sdl_gles2.h, demo/sdl_renderer/nuklear_sdl_renderer.h, demo/sfml_opengl2/nuklear_sfml_gl2.h, demo/sfml_opengl3/nuklear_sfml_gl3.h, demo/wayland_rawfb/nuklear_raw_wayland.h, demo/x11/nuklear_xlib.h, demo/x11_opengl3/nuklear_xlib_gl3.h, demo/x11_rawfb/nuklear_rawfb.h, demo/x11_rawfb/nuklear_xlib.h, demo/x11_xft/nuklear_xlib.h
Added missing include decelerations and in one case removed an unnecessary one form the platform headers in the `demo/` directory .
=> Added missing includes to the platform headers .

LICENSE, Readme.md
Moved licenses to a new file and put a brief notice + link in its place
=> Move copyright info to its own file

src/nuklear_internal.h, src/nuklear_layout.c, src/nuklear_math.c
=> Round layout widget position to nearest 0

demo/sdl_vulkan/.gitignore, demo/sdl_vulkan/Makefile, demo/sdl_vulkan/README.md, demo/sdl_vulkan/main.c, demo/sdl_vulkan/nuklear_sdl_vulkan.h, demo/sdl_vulkan/shaders/demo.frag, demo/sdl_vulkan/shaders/demo.vert, demo/sdl_vulkan/src/Makefile, demo/sdl_vulkan/src/README.md, demo/sdl_vulkan/src/nuklear_sdl_vulkan.in.h, demo/sdl_vulkan/src/nuklearshaders/nuklear.frag, demo/sdl_vulkan/src/nuklearshaders/nuklear.vert
Based on other SDL demos and GLFW Vulkan demo.
Closes #175
=> Add vulkan SDL backend and demo

demo/xcb_cairo/nuklear_xcb.h
=> nk_xcb_handle_event leaks

demo/xcb_cairo/nuklear_xcb.h
=> sets xcb window's title

demo/glfw_opengl2/nuklear_glfw_gl2.h, demo/glfw_opengl3/nuklear_glfw_gl3.h, demo/sdl_opengl2/nuklear_sdl_gl2.h, demo/sdl_opengl3/nuklear_sdl_gl3.h, demo/sdl_opengles2/nuklear_sdl_gles2.h, demo/sdl_renderer/nuklear_sdl_renderer.h, demo/sdl_vulkan/nuklear_sdl_vulkan.h, demo/x11/nuklear_xlib.h, demo/x11_xft/nuklear_xlib.h
select-all text handling was missing in demo.
=> Add select-all text handling in demo

demo/sdl_opengl2/nuklear_sdl_gl2.h, demo/sdl_opengl3/nuklear_sdl_gl3.h, demo/sdl_opengles2/nuklear_sdl_gles2.h, demo/sdl_renderer/nuklear_sdl_renderer.h, demo/sdl_vulkan/nuklear_sdl_vulkan.h, demo/sdl_vulkan/src/nuklear_sdl_vulkan.in.h
=> sdl: Fix SD_GetClipboardText memory leak

demo/glfw_opengl4/nuklear_glfw_gl4.h
This is a follow up PR to #780. By fixing the usage of bindless textures the bookkeeping code for the ids-to-handle translations is not needed any more. This PR removes it and the limitation of a fix `NK_GLFW_MAX_TEXTURES` constant.
*Side note: This PR also reorders the shader compilation error checking to make it more readable.*
=> Remove unnecessary indirection in glfe_opengl4 demo

demo/rawfb/nuklear_rawfb.h
This should reduce the overall number of calls to `nk_rawfb_color2int`, since it's no longer being called for every pixel and/or horizontal line.
=> Call nk_rawfb_color2int once per command
