- doc/nuklear.html
- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_edit.c
- src/nuklear_math.c
fix nk_do_edit autoscroll.
How to test:
Create an edit widget.
Enter a long text into the edit widget.
Press "home" so that widget autoscrolls to start of text.
Press "end" so that widget now should jump to end of text.
Previously you had to press "end" several times to jump to the end of text.
This patch fixes that (pressing "end" once will jump to the end of text).
> Scrollfix1

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear.h
Fixes intersect detection for the upper bound, see #18 for rationale.
> Fix off-by-one error in NK_INTERSECT

- demo/wayland_rawfb/Makefile
- demo/wayland_rawfb/main.c
- demo/wayland_rawfb/nuklear_raw_wayland.h
This implementation uses software rendering in native wayland client.
> Add pure C wayland demo

- demo/sdl_opengl2/main.c
- demo/sdl_opengl3/main.c
#66 
This fixed the error: conflicting types for 'SDL_main' when using mingw
> Added main arg params in demo/sdl_opengl

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_layout.c
Let me be the first to open a PR on this new repo :confetti_ball:
Copied from [here](https://github.com/vurtun/nuklear/pull/935)
Before:
After:
> Fix bug where width padding was applied twice

- example/Makefile
Script "example\Makefile" do not work on Windows_NT platform. I am added some minor changes to fix this.
> fix Makefile for Windows_NT

- demo/d3d11/nuklear_d3d11.h
- demo/d3d9/nuklear_d3d9.h
- demo/glfw_opengl2/nuklear_glfw_gl2.h
- demo/glfw_opengl3/nuklear_glfw_gl3.h
- demo/glfw_opengl4/nuklear_glfw_gl4.h
- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sfml_opengl2/nuklear_sfml_gl2.h
- demo/sfml_opengl3/nuklear_sfml_gl3.h
- demo/x11_opengl2/nuklear_xlib_gl2.h
- demo/x11_opengl3/nuklear_xlib_gl3.h
- example/canvas.c
- example/extended.c
- example/file_browser.c
- example/skinning.c
As mentioned in #97 
This change adds an `nk_buffer_clear` on the cmds buffer after each frame to stop it growing over time.
> Fix memory leak in demo and example code.

- Readme.md
Here is the fix for #114 using the github pages.
Setup is really simple: on project settings, go to Github Pages section and **enable** it
Github then shows that the project is available on github.io, so project README and documentation page are both available on [immediate-mode-ui.github.io/Nuklear](https://immediate-mode-ui.github.io/Nuklear)
I have updated the readme to link directly to the github.io page
> Documentation fix (solves #114)

- demo/glfw_opengl3/main.c
- demo/glfw_opengl3/nuklear_glfw_gl3.h
Port vurtun PR, fixes #107
@maddouri statement:
> Thanks for your interest in the PR. IMHO, not having a global state ought to be a requirement for all code samples.
> Unfortunately, I doubt that I would have enough resources to dedicate to porting vurtun/nuklear#760 to this repo.
>
> To anyone interested: please feel free to adapt my PR's code to this new repo :)
> demo/glfw_opengl3 Remove global state

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_edit.c
Draw frame border after background to prevent overlapping.
At least for `x11` and `gdi` back-ends.
Before:
After:
> fix: 'nk_edit' frame border drawing

- demo/glfw_opengl3/main.c
- demo/glfw_opengl3/nuklear_glfw_gl3.h
Using this header without the implementation is not possible because needed structs are not defined in the header only part. This PR solves this problem by making `struct nk_glfw` and `struct nk_glfw_device` public.
Note that a source implementing this backend still needs to include nuklear implementation too, because it uses some macros defined only in the implementation part of nuklear (i.e. `NK_MEMSET`). I have not been as deep as reviewing that part (not being sure of what should be done).
> nuklear_glfw_gl3.h without implementation

- nuklear.h
- package.json
- src/CHANGELOG
- src/HEADER
- src/nuklear.h
`NK_INCLUDE_STANDARD_VARARGS` needs the va_list type from **stdarg.h**.
So like `NK_INCLUDE_STANDARD_IO` which includes **stdio.h**, this one should include **stdarg.h**
Sorry for the multiple commits, I forgot to update the documentation and to regenerate **nuklear.h** from src directory.
> Include stdarg

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_menu.c
Issues with menu bar height calculation for groups. 
Before:
After:
Code to reproduce:
```c++
/* GUI */                                                                
if (nk_begin(ctx, "Demo", nk_rect(50, 50, 200, 200),                     
NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_SCALABLE|      
NK_WINDOW_CLOSABLE|NK_WINDOW_MINIMIZABLE|NK_WINDOW_TITLE))  
{                                                                        
nk_menubar_begin(ctx);                                               
nk_layout_row_dynamic(ctx, 50, 1);                                   
nk_button_label(ctx, "window nenu");                                 
nk_layout_row_dynamic(ctx, 300, 1);                                  
if (nk_group_begin(ctx, "group", NK_WINDOW_BORDER|NK_WINDOW_TITLE))  
{ …
```
> Fix 'nk_menubar' height calculation bug

- demo/wayland_rawfb/.gitignore
- demo/wayland_rawfb/Makefile
- demo/wayland_rawfb/main.c
- demo/wayland_rawfb/nuklear_raw_wayland.h
The wl_shell interface it previously used is deprecated and not implemented
by some compositors, like sway.
Fixes #134
> Migrate wayland demo to xdg_shell.

- demo/allegro5/nuklear_allegro5.h
Hello!
This is follow-up to #139 . I am so very sorry, I messed up the function name to load the bitmap, so it is not exported when Nuklear is built as dynamic library (and hence is unusable). This PR fixes it.
> Fixed naming bug in allegro5 backend image support

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_edit.c
How to test:
Construct two edit widgets.
Enter a long text into the first edit widget, so that the widget autoscrolls.
Click into second (still empty) edit widget.
Click into first edit widget again.
=> Text jums back, so that first character of text in first edit widget is visible again.
This patch keeps the scroll position of the edit widget constant.
> fix nk_do_edit: Keep scroll position when re-activating edit widget.

- .gitattributes
- src/build.py
This is my attempt and fixing this very unfortunate problem. Anyone with a windows installation that wants to help test this can do the following:
```
git clone https://github.com/Hejsil/Nuklear-1.git
cd Nuklear-1/src
git checkout newline-fix
paq.bat
git diff
```
`git diff` should hopefully show that nothing changed. If @zgcrowno could test this that would be great!
> Newline fix for paq script on windows

- demo/allegro5/nuklear_allegro5.h
Hello!
Currently Allegro5 backend allows to set custom font on initialization using [`nk_allegro5_font_create_from_file`](https://github.com/Immediate-Mode-UI/Nuklear/blob/bffe1037b2de63bd05f040f58b32bfca9877689e/demo/allegro5/nuklear_allegro5.h#L34) that wraps `nk_user_font` struct into [`NkAllegro5Font`](https://github.com/Immediate-Mode-UI/Nuklear/blob/bffe1037b2de63bd05f040f58b32bfca9877689e/demo/allegro5/nuklear_allegro5.h#L53) custom bookkeeping struct, but after that the font only could be set globally using [`nk_allegro5_font_set_font`](https://github.com/Immediate-Mode-UI/Nuklear/blob/bffe1037b2de63bd05f040f58b32bfca9877689e/demo/allegro5/nuklear_allegro5.h#L36) (which [wraps `nk_style_set_font`](https://github.com/Immediate-Mode-UI/Nuklear/blob/bffe1037b2de63bd05f040f58b32bfca987 …
> Added ability to use user fonts after initialization in allegro5 backend

- demo/overview.c
I got a warning about this from my compiler (cl.exe). I tested it both ways, and the behavior is the same, except for the compiler warning no longer occurs after my change.
> use integer for integer bound

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_combo.c
The changes made ensure that when an nk_combo has no symbol associated with it, the symbol is neither drawn nor reserved any space in the header.
> Make nk_combo Header Symbols Optional.

- demo/glfw_opengl3/nuklear_glfw_gl3.h
- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_pool.c
- Buffer size was under counted by using nk_page_data rather than nk_page_element.
- Buffer size was over counted by sizing for an unused element (page header contains the first one).
- Original code was not unsafe as the overcounting was larger than the under counting for the default pool size.
- Sized pages based on pool capacity rather than hard-coded value since it's configurable.
- Added and assert for safety.
> fix bugs in computing pooled allocation sizes

- demo/sdl2surface_rawfb/Makefile
- demo/sdl2surface_rawfb/main.c
- demo/sdl2surface_rawfb/sdl2surface_rawfb.h
The other sdl  demo backends all use OpenGL, which defeats the
purpose of using SDL_Renderer for portabilty.
This is maybe not as good as a full SDL_Renderer backend, but it
is more flexible. For most applications software rendering of the
UI is more than fast enough.
> Add a rawfb backend which uses SDL_Surface's for output.

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_font.c
Compiling in Ubuntu 20.04 with gcc 9.3.0 throws an error:
../../nuklear.h:16579:17: error: C++ style comments are not allowed in ISO C90
16579 |                 // Need to zero this, or it will carry over from a previous
|                 ^
What I did:
```
git clone https://github.com/Immediate-Mode-UI/Nuklear
cd demo/x11_rawfb/
make
```
> [fix][error] C++ style comments are not allowed in ISO C90

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_font.c
- src/nuklear_internal.h
This PR seeks to resolve issue #231 ISO ansi pedantic compilation error (gcc).
It makes changes to src/nuklear_internal.h and to src/nuklear_font.h to allow them to compile w/ gcc flags '-std=c89 -pedantic'
> Fix C89 compilation errors

- demo/d3d11/nuklear_d3d11.h
Issue #236 
When defining NK_UINT_DRAW_INDEX to increase the size of nk_draw_index from ushort to a uint to allow drawing a lot more on a window, the D3D11 implementation doesn't handle the change properly and exhibits the behavior explained in the Issue. 
This Pull Request implements a change that allows the D3D11 implementation to work regardless if you have the NK_UINT_DRAW_INDEX defined or not.
> Made D3D11 implementation work when using NK_UINT_DRAW_INDEX

- demo/glfw_opengl2/nuklear_glfw_gl2.h
- demo/glfw_opengl3/nuklear_glfw_gl3.h
- demo/glfw_opengl4/nuklear_glfw_gl4.h
- demo/sdl2surface_rawfb/sdl2surface_rawfb.h
- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sfml_opengl2/nuklear_sfml_gl2.h
- demo/sfml_opengl3/nuklear_sfml_gl3.h
- demo/x11/nuklear_xlib.h
- demo/x11_opengl2/nuklear_xlib_gl2.h
- demo/x11_opengl3/nuklear_xlib_gl3.h
- demo/x11_rawfb/nuklear_rawfb.h
- demo/x11_rawfb/nuklear_xlib.h
- demo/x11_xft/nuklear_xlib.h
All the backend implementations demos make use of the NK_MEMSET macro.
However NK_MEMSET is not defined in Nuklear's public header, but in it's private implemenation. Specifically in nuklear_internal.h As the name suggests, NK_MEMSET is meant for nuklear's internal implementation.
Even the single header build file makes this obvious: nuklear.h is --pub, but nuklear_internal.h is --priv1 .
- But why change it?
Although Nuklear is a single header library, it sometimes makes sense to split it for faster compilation. The Implementation can be precompiled into an object file and the header can be precompiled into a precompiled header object file. This allows blazing fast recompilation and instant response from linting. However, because the backend implementations mix public and internal …
> Change NK_MEMSET to memset() in demos, to prevent compilation errors when Nuklear.h is split or NK_IMPLEMENTATION is undefined

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_layout.c
- src/nuklear_panel.c
- src/nuklear_pool.c
- src/nuklear_scrollbar.c
This addresses the `-Wconversion` and `-Wsign-conversion` warnings.
> Fix warnings about sign conversion

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_font.c
This wild `memset` prevented me from compiling nuklear without a c standard library :)
> Replace usage of memset in nk_font_atlas_bake with NK_MEMSET

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear.h
My attempt at fixing #94 by using compiler builtins when available.
> Use compiler builtins for NK_OFFSETOF when possible

- example/canvas.c
On macOS (or just retina/hi-dpi displays), the window size is not necessarily the render size so, glfwGetFramebufferSize must be used instead of glfwGetWindowSize in the render loop.
So originally it would look like this:
But with my change it now looks like this:
> Fix canvas example not rendering fully on macOS

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear_property.c
Re-created PR#27 (not me) since this is still an issue, gcc 11.1 on Linux here.
> Fix "'num_len' may be used uninitialized" in nk_do_property

- nuklear.h
- package.json
- src/CHANGELOG
- src/nuklear.h
Early OSX compiler toolchains used gcc 2.95.2, 3.1 and 3.3, and offsetof was not added until gcc 4.
> GCC __builtin_offsetof only exists in version 4 and later

- Readme.md
- demo/overview.c
- demo/x11_opengl3/nuklear_xlib_gl3.h
- doc/nuklear.html
- doc/stddoc.c
- example/stb_image.h
- nuklear.h
- src/CHANGELOG
- src/HEADER
- src/nuklear.h
- src/nuklear_vertex.c
- src/stb_rect_pack.h
- src/stb_truetype.h
Found via `codespell -q 3 -L acount,modifyable,nd,pixelx,seperator,te,vertexes`
> Fix various typos

- demo/allegro5/nuklear_allegro5.h
Hello! This tiny PR fixes `unused parameter 'height'` warning in Allegro5 demo.
> Fix warning in Allegro5 demo

- Readme.md
- clib.json
- src/CHANGELOG
The clib package manager has deprecated package.json in favor of clib.json (probably to reduce confusion between clib and other package managers, e.g. npm). As far as I can tell, there's no difference in file format, only in name.
> Rename package.json to clib.json

- demo/allegro5/Makefile
- demo/allegro5/main.c
- demo/allegro5/nuklear_allegro5.h
- demo/d3d11/nuklear_d3d11.h
- demo/d3d9/main.c
- demo/d3d9/nuklear_d3d9.h
- demo/gdi/nuklear_gdi.h
- demo/gdip/nuklear_gdip.h
- demo/glfw_opengl2/Makefile
- demo/glfw_opengl3/Makefile
- demo/glfw_opengl3/nuklear_glfw_gl3.h
- demo/glfw_opengl4/Makefile
- demo/glfw_opengl4/nuklear_glfw_gl4.h
- demo/overview.c
- demo/sdl2surface_rawfb/Makefile
- demo/sdl2surface_rawfb/main.c
- demo/sdl2surface_rawfb/sdl2surface_rawfb.h
- demo/sdl_opengl2/Makefile
- demo/sdl_opengl3/Makefile
- demo/sdl_opengles2/Makefile
- demo/sdl_opengles2/main.c
- demo/x11_opengl2/Makefile
- demo/x11_opengl3/Makefile
- demo/x11_rawfb/nuklear_rawfb.h
- demo/x11_rawfb/nuklear_xlib.h
- demo/x11_xft/nuklear_xlib.h
This was originally submitted as vurtun/nuklear#814. It also supercedes PR #39.
> Build all demos as C89

- .editorconfig
[EditorConfig](https://editorconfig.org) is a utility for various code editors which will automatically configure the editor to manage whitespace as desired.
> Add EditorConfig to manage editor whitespace

- clib.json
- nuklear.h
- src/CHANGELOG
- src/nuklear_panel.c
fixes #132
This is not quite done. Currently having this funny bug in the node editor demo.
> Fix layout bounds not accounting for padding

- nuklear.h
- src/CHANGELOG
This changes the versioning strategy from `x.yy.zz` to `x.y.z` to more align with [semantic versioning](https://semver.org/).
Fixes #382
> changelog: Use x.y.z for versioning, rather than x.yy.zz

- clib.json
- nuklear.h
- src/CHANGELOG
- src/nuklear_panel.c
Reverts Immediate-Mode-UI/Nuklear#156
@aganm @Hejsil This change reverts the layout bounds change. May be worth considering removing the change until we fix it for good. What do you think?
> Revert "Fix layout bounds not accounting for padding"

- clib.json
- nuklear.h
- src/CHANGELOG
- src/HEADER
- src/nuklear_internal.h
- src/nuklear_math.c
- src/nuklear_vertex.c
Noticed that the docs referenced `NK_SQRT`, which didn't exist, and then noticed that the `nk_inv_sqrt` wasn't overridable. So this change fixes that up.
> Allow overriding the NK_INV_SQRT function

- demo/sdl_renderer/nuklear_sdl_renderer.h
This commit addresses an issue where the Metal render driver (default on macOS) could not handle the clipping rectangle `{-8192, -8192, 16384, 16384}` and would simply draw nothing to the screen. The solution is to ensure the cliprect coordinates are not negative, which also doesn't seem to break the other render drivers (tested OpenGL).
> Fix Metal rendering in sdl_renderer

- demo/common/file_browser.c
Icons are now displayed in a "Compact list view" rather than a "icon view"
> Better Display file icons in the filebrowser

- demo/glfw_opengl3/nuklear_glfw_gl3.h
While it doesn't fix the issue @tree786isback, it is a good thing to cast the void*'s correctly.
References https://github.com/Immediate-Mode-UI/Nuklear/issues/433
> glfw_gl3: Cast the void* to a nk_glfw*

- demo/common/file_browser.c
-Adds visible boundary to file icon box;
-Adds a 'cancel' button that closes the file dialog;
-Adds a 'save' button that should be used for the save() routine defined by the user. 
Of course, the user can also easily change the 'save' to 'open'.
> Further improve file_browser.c

- nuklear.h
- src/CHANGELOG
- src/nuklear.h
- src/nuklear_input.c
This modifies the trigger behavior of buttons to only activate when the
mouse was also over the same button on the mouse button down event.
This fixes #357 to the best of my knowledge
Side note:
I also modified my version of Nuklear I use to apply the same logic for
hover, because I use Nuklear for touch input devices where traditional
hover behavior tends to be misleading. I left this out for now because
I can imagine that this could be seen as wrong/faulty behavior by some.
> Button behavior `NK_BUTTON_TRIGGER_ON_RELEASE`

- demo/common/file_browser.c
It is no longer necessary, since string comparison is now carried out by Nuklear API.
> file_browser.c - remove #include <string.h>

- demo/sdl_renderer/main.c
This commit resolves two issues with high-DPI display rendering:
1. The coordinates were not scaled properly, resulting in tiny output
and misalignment of actual cursor position with apparent position;
this is fixed by calling SDL_SetRenderScale with appropriate scaling
factors determined by comparing the window size to the renderer's
output size
2. The fonts were not oversampled, resulting in excessively blurry text;
this is fixed by setting oversample_h and oversample_v on the
font_config according to the scaling factors
> Fix high-DPI scaling in sdl_renderer

- demo/gdi/nuklear_gdi.h
This PR is based on #385 and correctly implements (filled) arc drawing, as well as circle stroke drawing in GDI.
It also adds the select all keyboard shortcut.
> Added working filled and outlined arc drawing to GDI binding

- nuklear.h
- src/CHANGELOG
- src/nuklear.h
- src/nuklear_button.c
- src/nuklear_input.c
This adds a new `nk_input_has_mouse_click_in_rect_button` function that is being used only by buttons. This allows `nk_input_has_mouse_click_in_rect` to act as its name suggests while still allowing for the behavior introduced in #448 to work as described.
> Fix regression introduced in #448

- nuklear.h
- src/CHANGELOG
- src/nuklear.h
This adds a check on `__aarch64__` to fix Apple Silicon selecting the incorrect `NK_SITE_TYPE` and `NK_POINTER_TYPE`. Reported by @aiq over at https://github.com/RobLoach/raylib-nuklear/pull/37 .
> Fix Apple Silicon with incorrect NK_SITE_TYPE and NK_POINTER_TYPE

- demo/d3d11/nuklear_d3d11.h
- demo/d3d12/nuklear_d3d12.h
- demo/d3d9/nuklear_d3d9.h
- demo/glfw_opengl2/nuklear_glfw_gl2.h
- demo/glfw_opengl3/nuklear_glfw_gl3.h
- demo/glfw_opengl4/nuklear_glfw_gl4.h
- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sdl_renderer/nuklear_sdl_renderer.h
- demo/sfml_opengl2/nuklear_sfml_gl2.h
- demo/sfml_opengl3/nuklear_sfml_gl3.h
- demo/x11_opengl2/nuklear_xlib_gl2.h
- demo/x11_opengl3/nuklear_xlib_gl3.h
- doc/index.html
- example/canvas.c
- example/extended.c
- example/file_browser.c
- example/skinning.c
- nuklear.h
- src/CHANGELOG
- src/nuklear.h
- src/nuklear_font.c
- src/nuklear_vertex.c
This builds upon https://github.com/Immediate-Mode-UI/Nuklear/pull/469 to replace the null variable across other locations in the codebase.
> Rename `null` texture field to `tex_null`

- src/nuklear.h
- src/nuklear_vertex.c
"null" is a reserved keyword in most languages, to make the usage of the library easier for other languages (and other compilers zig/D), let's rename it, it also is a better name in my opinion, null should be reserved in C too imo
> Rename null texture field to name friendlier to language bindings

- demo/allegro5/main.c
- demo/d3d11/main.c
- demo/d3d12/main.c
- demo/d3d9/main.c
- demo/gdi/main.c
- demo/gdip/main.c
- demo/glfw_opengl2/main.c
- demo/glfw_opengl3/main.c
- demo/glfw_opengl4/main.c
- demo/sdl_opengl2/main.c
- demo/sdl_opengl3/main.c
- demo/sdl_opengles2/main.c
- demo/sdl_renderer/main.c
- demo/sfml_opengl2/main.cpp
- demo/sfml_opengl3/main.cpp
- demo/x11/main.c
- demo/x11_opengl2/main.c
- demo/x11_opengl3/main.c
- demo/x11_rawfb/main.c
- demo/x11_xft/main.c
Not a big deal, but it's annoying to have to modify the demos code to see the effect of styles, then revert to keep on the upstream commit.
It's already possible to use defines to select which demos to include, for example:
```
CFLAGS='-DINCLUDE_CANVAS' make
```
This PR adds the possibility to select the used style when `INCLUDE_STYLE` is defined:
```
CFLAGS='-DINCLUDE_OVERVIEW -DINCLUDE_STYLE -DSTYLE_WHITE` make
```
All demos using the `set_style()` function have been updated, and that does not change the default behavior.
> demos: set style with defines

- demo/glfw_opengl3/nuklear_glfw_gl3.h
Addressing #516
This resolves a false UBSan trip caused by treating the element offset in `glDrawElements` as a pointer
This parameter is effectively an offset but is taken as a `void*`. By not storing the offset as a pointer, UBSan no longer tools the offset to check for null pointer overflow.
OpenGL has a tendency to take offsets which are applied on the GPU as pointers, but they are just offsets so it's perfectly fine to do this.
> Fixed UBSan trip in GLFW OpenGL3 demo backend

- demo/gdi_native_nuklear/window.h
The calling convention of a WNDPROC is specified as being 'CALLBACK'.
> gdi_native: Fix calling convention problem

- demo/allegro5/nuklear_allegro5.h
Hello! This tiny PR consists of a few string handling tweaks in allegro5 backend:
* local variable `strcpy` renamed to `str`, as per SEI CERT [DCL01-C](https://wiki.sei.cmu.edu/confluence/display/c/DCL01-C.+Do+not+reuse+variable+names+in+subscopes).
* `malloc` and manual null-terminator addition replaced with `calloc`.
* added missing `NULL` from allocator check.
* `strcpy` replaced with `strncpy` for better security.
> demo/allegro5: minor string-related tweaks

- clib.json
- nuklear.h
- src/CHANGELOG
- src/nuklear_font.c
In stbtt_PackFontRangesGatherRects, it skips packing when glyphs are missing. Resulting in incorrect glyphs when nk_font_bake reading these ranges rects data. Referring to the way IMGUI handles it, we skip the rect data check.
ref #399 
load font:
before:
after:
> Fix incorrect glyph index in nk_font_bake

- nuklear.h
- src/nuklear.h
In the docs the variable `size` is declared but then `ratio` is used instead. This fixes that.
> fix variable name in docs

- demo/gdi/nuklear_gdi.h
- demo/gdip/nuklear_gdip.h
I don't know why it wasn't like that before
> Fix for GDI and GDI+ 

- nuklear.h
- src/nuklear.h
PowerPC 64-bit platforms use the lowercase `__ppc64__` on Apple systems (based on comments I've seen).  However lowercase `__ppc64__` is not defined by GCC; uppercase `__PPC64__` is.  This pull request adds a check for the uppercase macro so that compiling Nuklear.h works on systems that use GCC, like Debian GNU/Linux ppc64le.
> Use __PPC64__ macro for GCC detection

- clib.json
- nuklear.h
- src/nuklear_button.c
When calculating the width and height of the content rect of a button, only the border of one side is being taken into account. Instead the border width needs to be multiplied by two before subtracting from the bounds. This is being done for padding and rounding, but not border, which is resulting in text being misaligned. The screenshots below demonstrate the issue (I've exaggerated the borders to make it easier to see the effect).
Before:
After:
> Fix button text alignment error.

- .github/workflows/ccpp.yml
- .github/workflows/create-tag.yml
This brings changes to keep up with the GitHub Actions internals (among other changes). This will remove some of the deprecation warnings in the GitHub Actions UI.
> ci: Update to `actions/checkout@v4`.

- nuklear.h
- src/nuklear_color.c
Hi! Building `Nuklear` with MSVC (`Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33134 for x64`) results in following W3+ level warnings:
```
Nuklear\nuklear.h(7665): error C2220: the following warning is treated as an error
Nuklear\nuklear.h(7665): warning C4244: '=': conversion from 'const float' to 'nk_byte', possible loss of data
Nuklear\nuklear.h(7666): warning C4244: '=': conversion from 'const float' to 'nk_byte', possible loss of data
Nuklear\nuklear.h(7667): warning C4244: '=': conversion from 'const float' to 'nk_byte', possible loss of data
```
This fix resolves the issue by explicit safe cast which assumed to be safe. Thanks!
> Suppress compiler `possible loss of data` warning with explicit cast

- demo/common/overview.c
The overview demo uses some `nk_bool`s that are typed as `int`s. While things still do function, if you're using `NK_INCLUDE_STANDARD_BOOL`, it breaks compilation. This change fixes the `nk_bool`s to be actual `nk_bool`s.
> demo: Fix overview's `nk_bool` usage

- demo/sdl_opengl2/main.c
- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/main.c
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/main.c
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sdl_renderer/main.c
- demo/sdl_renderer/nuklear_sdl_renderer.h
Moved grab handling out of `nk_sdl_handle_event` to `nk_sdl_handle_grab`, which is now called outside of the event loop.
This change makes the logic similar to the GLFW demos and fixes issues with missed grab state changes and mouse cursor disappearing.
Discussed in https://github.com/Immediate-Mode-UI/Nuklear/issues/608
> Fix missed grab state changes in SDL demos

- nuklear.h
- src/CHANGELOG
- src/nuklear_contextual.c
- src/nuklear_panel.c
- src/nuklear_popup.c
- src/nuklear_property.c
- src/nuklear_tooltip.c
This PR is intended to fix multiple warnings 
`warning: bitwise operation between different enumeration types XXX and YYYY is deprecated `
raised when compiling in C++20
Each time I updated Nuklear on my side I did those changes, today I decided to make them once and for all with a PR :smile: 
Fixes #170
> Fix bitwise operations warnings in C++20

- demo/glfw_vulkan/main.c
This PR contains changes I needed for the glfw_vulkan demo to function in a reasonable manner (launch + window resizing) on my Void Linux machine.
`40a172b` - It is valid to continue a render process in the event that `vkAcquireNextImageKHR` returns `VK_SUBOPTIMAL_KHR`. The implementation already correctly handles recreating the swapchain when necessary so no other changes were needed beyond preventing the error-out.
`03aa308` - Vulkan may create more swapchain images than requested via `minImageCount` to `vkCreateSwapchainKHR`. In my testing on two different machines, `vkGetSwapchainImagesKHR` was returning `minImageCount + 1` when queried, causing me to hit this error-out. The demo works without any other changes beyond preventing the error-out. …
> Minor fixes for GLFW Vulkan Demo

- example/file_browser.c
`strncpy()`'s pointer parameters are marked `restrict`, but when `file_browser_reload_directory_content()` was being called to reload the directory that was currently open:
```c
file_browser_reload_directory_content(browser, browser->directory)
```
it would try to copy its path buffer to itself, causing undefined behavior. The solution uses `memmove()`, which can handle overlapping pointers.
Found with Address Sanitizer.
> Fix undefined behavior in `strncpy()` call

- demo/common/overview.c
This fixes an ISO warning on mixed declarations in the overview demo.
```
demo/common/overview.c:15:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
15 |         static nk_bool disable_widgets = nk_false;
|         ^~~~~~
```
> Fix overview mixed declarations

- demo/common/overview.c
- nuklear.h
- src/nuklear_property.c
This adds the ability to use `##` as a prefix for a property name to have the label not show at all. Also adds a demonstration in the overview demo.
> property: Allow optional labels for properties with #

- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sdl_renderer/nuklear_sdl_renderer.h
Definitons are available in implementation mode but not header-only mode
> Fix missing nk_sdl_handle_grab declarations in SDL demo headers

- demo/sdl_renderer/nuklear_sdl_renderer.h
change SDL include path to the recommended path
> Proposal: Update nuklear_sdl_renderer.h to use recommended path for SDL.h

- nuklear.h
- src/nuklear.h
- src/nuklear_context.c
- src/nuklear_font.c
- src/nuklear_internal.h
- src/nuklear_pool.c
- src/nuklear_text_editor.c
- src/nuklear_util.c
The `nk_allocator` struct consists of 3 fields, `userdata` (application-specified ptr), `alloc` (allocate function), and `free` (deallocate function). None of these are modified once provided by the library user as far as I can tell, so it should be safe to make this struct `const` in all API parameters.
Since stb-truetype uses a `void*` for allocation data, a cast is necessary. But, since the `nk_stbtt_malloc`/`nk_stbtt_free` implementations don't modify the `nk_allocator` (as the potentially mutable allocator is stored indirectly in `nk_allocator.userdata`), this should be fine as well.
> Add `const` qualifiers to `nk_allocator` in more places.

- src/nuklear_panel.c
example:
nk_style_push_float(ctx, &ctx->style.window.rounding, your_value);
nk_begin(...);
nk_end(...);
nk_style_pop_float(ctx);
> Fix rounding of panels

- demo/common/overview.c
- demo/sdl_renderer/main.c
- nuklear.h
- src/nuklear.h
- src/nuklear_button.c
This change adds triangle outline symbols.
> Add triangle outline symbols

- nuklear.h
- src/nuklear_vertex.c
Not at all a critical change request, but I'll leave it here for consideration when the time arrises.
The original code was distinctly unclear. I've tried to keep to the surrounding code style while making the code flow more comprehensible.
I've not looked elsewhere for any other similar occurrences; this became apparent while investigating a specific line of thought.
> Improve one poor case of indentation

- demo/glfw_opengl2/nuklear_glfw_gl2.h
- demo/glfw_opengl3/nuklear_glfw_gl3.h
- demo/glfw_opengl4/nuklear_glfw_gl4.h
- demo/glfw_vulkan/nuklear_glfw_vulkan.h
- demo/glfw_vulkan/src/nuklear_glfw_vulkan.in.h
All of the glfw demo headers unset shift keypresses when the ctrl key is not also down.
I can't think of a reason this would be desired and it appears no other demo code does this.
Unless I'm mistaken, simply removing these lines leaves us with the desired behaviour.
> Quickfix glfw shift-key handling

- nuklear.h
- src/nuklear.h
Getting the following error with Emscripten, complaining that __builtin_offset isn't available. This disables the usage of it when on Emscripten...
```
nuklear.h:8978:38: error: defining a type within '__builtin_offsetof' is a C23 extension [-Werror,-Wc23-extensions]
8978 |     NK_STORAGE const nk_size align = NK_ALIGNOF(struct nk_command);
```
> Fix for NK_OFFSETOF on Emscripten

- nuklear.h
- src/nuklear_window.c
`nk_window_set_position` and `nk_window_set_size` allow updating an in process window while `nk_window_set_bounds` does not even though the effect is equivalent.
> Remove unnecessary assert

- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
Adds delta_time_seconds for the following.
1. sdl_opengl2
2. sdl_opengl3
3. sdl_opengles2
>  Add delta_time_seconds to a 3 more renderers #627

- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sfml_opengl2/nuklear_sfml_gl2.h
- demo/sfml_opengl3/nuklear_sfml_gl3.h
- demo/x11/nuklear_xlib.h
- demo/x11_opengl2/nuklear_xlib_gl2.h
- demo/x11_opengl3/nuklear_xlib_gl3.h
- demo/x11_xft/nuklear_xlib.h
Adds delta_time_seconds for the following.
1. x11
2. x11_opengl2
3. x11_opengl3
4. x11_xft
5. sfml_opengl2
6. sfml_opengl3
> Add delta_time_seconds to X11 and SFML renderers

- demo/allegro5/nuklear_allegro5.h
- demo/common/overview.c
- demo/glfw_opengl2/nuklear_glfw_gl2.h
- demo/glfw_opengl3/nuklear_glfw_gl3.h
- demo/glfw_vulkan/nuklear_glfw_vulkan.h
- demo/rawfb/nuklear_rawfb.h
- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sdl_renderer/main.c
- demo/sdl_renderer/nuklear_sdl_renderer.h
This change adds `delta_time_seconds` to a few of the renderers. Would love some help on supporting some of the others.
Fixes #627
> Add delta_time_seconds to a few renderers

- src/nuklear.h
- src/nuklear_util.c
Removes `const` from `endptr` argument to allow it to function as intended.
```c
/* From 1989 ANSI standard 4.10.1.4 */
double strtod(const char *nptr, char **endptr);
```
This should fix #678.
> Fixes for nk_strtod, nk_strtof, and nk_strtoi

- demo/common/overview.c
This adds the `time.h` include to the top of overview.c so that the renders don't need to include it manually.
> demo: Add time.h to overview.c

- demo/common/overview.c
This adds the required C headers directly to the top of the overview.c demo so that they don't need to be added in the renders themselves.
> demo: Add headers to overview.c

- demo/xcb_cairo/nuklear_xcb.h
Function `NK_API int nk_cairo_render(struct nk_cairo_context *cairo_ctx, struct nk_context *nk_ctx)` returns an int but `return;` is used twice. Now replaced with `return nk_false;`. This makes for clean compilation with both C89 _and_ C99.
> Update nuklear_xcb.h: eliminate two warnings in C99 mode

- demo/allegro5/nuklear_allegro5.h
Hey. This pull request makes allegro5 backend take the image region into account for `NK_COMMAND_IMAGE` command. Without that, it is impossible to e.g. correctly render 9-slice, consider:
before:
after:
I suspect similar problem is present in gdi, gdi_native, gdip, rawfb, x11 and x11_xft backends, but unfortunately I lack the knowledge nor time to fix those.
> allegro5: take image region into account for NK_COMMAND_IMAGE

- src/nuklear_font.c
Original website was compromised and is serving malware
Changed it for the author's github page instead
> Update proggyfont urls

- demo/d3d11/nuklear_d3d11.h
Behaviors match the ones in sdl demos.
I may add hi-dpi support to the d3d demo in similar fashion to how the sdl opengl ones work. That will be a separate PR.
> Add up/down/ctrl-b/ctrl-e key handling to d3d11 demo

- demo/rawfb/x11/Makefile
- demo/x11/Makefile
- demo/x11_xft/Makefile
Some of the demos built out their binaries as `zahnrad`, which doesn't match the rest of the `demo` builds. This consolidates them to `demo`.
> demo: Rename zahnrad binaries to demo

- demo/glfw_vulkan/main.c
- demo/glfw_vulkan/nuklear_glfw_vulkan.h
- demo/glfw_vulkan/src/nuklear_glfw_vulkan.in.h
Few small things improving the Vulkan demo code.
> Improve Vulkan demo

- nuklear.h
- src/nuklear.h
- src/nuklear_buffer.c
- src/nuklear_color.c
- src/nuklear_combo.c
- src/nuklear_draw.c
- src/nuklear_font.c
- src/nuklear_internal.h
- src/nuklear_layout.c
- src/nuklear_popup.c
- src/nuklear_string.c
- src/nuklear_style.c
- src/nuklear_table.c
- src/nuklear_widget.c
- src/nuklear_window.c
This patch adds `const` to pointers to data types which aren't modified.
There are few minor issues remaining - I did not changed these but please inform me what's your opinion on these:
- `nk_group_get_scroll` -  unlike with other getters, this getter can not use const context because the implementation modifies the context on one branch (the value is cached and created on-demand, which means getters need to be able to create it too)
- `nk_find_value` - the use of `const` would be questionable here, especially given the fact that the function returns non-const pointer. Perhaps it needs a second overload with both const input and const output?
- `nk_combo_callback`, `nk_combobox_callback` - shouldn't `item_getter` be changed from `void(*)(void*, int, const char**)` to `const …
> const correctness in public API

- nuklear.h
- src/nuklear.h
- src/nuklear_buffer.c
- src/nuklear_color.c
- src/nuklear_combo.c
- src/nuklear_draw.c
- src/nuklear_font.c
- src/nuklear_internal.h
- src/nuklear_layout.c
- src/nuklear_popup.c
- src/nuklear_string.c
- src/nuklear_style.c
- src/nuklear_table.c
- src/nuklear_widget.c
- src/nuklear_window.c
Reverts Immediate-Mode-UI/Nuklear#721
> Revert "const correctness in public API"

- demo/allegro5/main.c
- demo/d3d11/main.c
- demo/d3d12/main.c
- demo/d3d9/main.c
- demo/gdi/main.c
- demo/gdip/main.c
- demo/glfw_opengl3/main.c
- demo/glfw_opengl4/main.c
- demo/rawfb/sdl/main.c
- demo/rawfb/wayland/main.c
- demo/rawfb/x11/main.c
- demo/sdl_opengl2/main.c
- demo/sdl_opengl3/main.c
- demo/sdl_opengles2/main.c
- demo/sdl_renderer/main.c
- demo/sfml_opengl2/main.cpp
- demo/sfml_opengl3/main.cpp
- demo/x11/main.c
- demo/x11_opengl2/main.c
- demo/x11_opengl3/main.c
- demo/x11_xft/main.c
- demo/xcb_cairo/main.c
This enables the overview demo by default across all renderer examples. I've found it kind of annoying to re-enable the overview when testing components out, it would be nice to have this enabled by default.
> demo: Enable Overview by default

- Makefile
- src/build.py
The top level makefile has been upgraded to handle the building of everything in the project. Demos are recursively built, documentation is created, and Nuklear.h gets paq'd.  This does not break the previous build system, only adds a new path.
In order to make this happen, a small modification to `build.py` needed to happen to allow space delimited lists of files. Note, this change is backwards compatible.
Using the makefile at the top level for the building is not only familiar to C developers; but also provides better control and build capabilities to any automated systems. Multi-threaded building and processing, plus inherited compiler variables can help to simplify more advanced build procedures while providing a clean and common way for developers to make future adjustments.
After …
> Makefile Upgrade

- .github/workflows/docs.yml
- Readme.md
- doc/Doxyfile
This is an attempt to fix issue #730 since the original `gh-pages` branch is not fed anymore (with `.gitignore` changes).
I'm not an expert at all with Doxygen and github actions, so that might need more work (help is welcome).
With this, a few hints:
* I have removed README.md as start page, because it was not giving much and the _Documentation_ link was conflicting, instead the start page is made from `src/HEADER.md`
* The build generates a lot of warnings and errors. I suppose warnings can be fixed in the future from source files. Errors seem to come from the missing `dot` command (an additional package might be added to the required docker image before running doxygen)
* Once merged, `Pages` settings of the repository need to be changed because the generated doc is done in the root of …
> Restore documentation on github pages with Doxygen generated doc

- nuklear.h
- src/nuklear_util.c
This fixes `nk_strtoi()` expecting a `char**`, but getting a `const char**`.
> Fix `nk_strtoi()` const type usage

- demo/xcb_cairo/Makefile
- demo/xcb_cairo/nuklear_xcb.h
> xkbcommon support

- demo/common/style_configurator.c
- demo/sdl_opengl3/main.c
- demo/style_configurator.c
I made this for myself it working on my own Nuklear projects and also to help me understand how the various styles work and interact.
I think it (and the individual functions) would be useful to others both for app developers and developing and debugging Nuklear itself.  I could also see adding more configuration for values that aren't (currently) exposed in the style structures but figured I'd leave that for future work.
While I've been testing it manually/informally while I've written it, there was a lot of copy/pasting involved so I'm sure it's inevitable that a few bugs slipped through, which is why this is marked as a RFC.  I definitely want people to try it on more backends (I tested on sdl_opengl3), but also just want general suggestions/critiques.
> Style Configuration Tool RFC

- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sdl_renderer/nuklear_sdl_renderer.h
- demo/sdl_vulkan/nuklear_sdl_vulkan.h
If you tell a user they can submit with Enter and then it doesn't work, well... they don't care that the numpad Enter is technically a different key.  They have a point, they both are labeled "Enter" on most keyboards.
I can go through the other backends adding support but before I do I want to get feedback on my approach.  I can't think of any reason we'd want/need to add NK_KEY_KP_ENTER to nuklear itself because I can't think of a case we'd actually want distinct behavior for regular Enter/Return vs Numpad Enter.  If anyone can think of a convincing case I'll make the internal changes instead.
In either case I would need help testing several of them, specifically the windows backends, but possibly some of the more esoteric ones as well.
> Support numpad Enter with SDL backends

- clib.json
- nuklear.h
- src/CHANGELOG
- src/nuklear.h
My compiler (gcc 12) gives a compiler error:
nuklear.h:4846:10: note: while referencing ‘string’
nuklear.h: In function ‘nk_draw_text’:
nuklear.h:9762:16: error: array subscript [0, 0] is outside array bounds of ‘char[1]’ [-Werror=array-bounds]
nuklear.h:4846:10: note: while referencing ‘string’
Fixed my making it size 2.
> Fix array subscript [0, 0] is outside array bounds of ‘char[1]’

- demo/glfw_opengl4/nuklear_glfw_gl4.h
This MR fixes some issues with the way [bindless textures](https://www.khronos.org/opengl/wiki/Bindless_Texture) are uses in the glfw_opengl4 demo.
This MR closes #190, #568 and #579
The current implementation leads in a few cases to segmentation faults and compile errors. Mostly on AMD cards (my guess is on intel too, nvidia should be fine). Some of them are masked behind segmentation faults in mesa:
<details><summary>Stacktrace</summary>
<pre>
(gdb) bt
#0  convert_component () at ../mesa-24.3.4/src/compiler/glsl/ast_function.cpp:1132
#1  0x0000743e99a4c7bb in ast_function_expression::hir () at ../mesa-24.3.4/src/compiler/glsl/ast_function.cpp:2405
#2  0x0000743e99a5ac82 in process_initializer () at ../mesa-24.3.4/src/compiler/glsl/ast_to_hir.cpp:4691
#3  ast_declarator_list::hir () at …
> Fix glfw_opengl4 bindless textures

- demo/allegro5/main.c
- demo/allegro5/nuklear_allegro5.h
- demo/d3d11/nuklear_d3d11.h
- demo/d3d12/nuklear_d3d12.h
- demo/d3d9/nuklear_d3d9.h
- demo/gdi/nuklear_gdi.h
- demo/gdi_native_nuklear/nuklear_gdi.h
- demo/gdip/nuklear_gdip.h
- demo/glfw_opengl2/main.c
- demo/glfw_opengl2/nuklear_glfw_gl2.h
- demo/glfw_opengl3/nuklear_glfw_gl3.h
- demo/glfw_opengl4/Makefile
- demo/glfw_opengl4/nuklear_glfw_gl4.h
- demo/glfw_vulkan/main.c
- demo/glfw_vulkan/nuklear_glfw_vulkan.h
- demo/sfml_opengl2/Makefile
- demo/sfml_opengl2/nuklear_sfml_gl2.h
- demo/sfml_opengl3/nuklear_sfml_gl3.h
- demo/x11/nuklear_xlib.h
- demo/x11_opengl2/nuklear_xlib_gl2.h
- demo/x11_opengl3/nuklear_xlib_gl3.h
- demo/x11_xft/nuklear_xlib.h
- demo/xcb_cairo/nuklear_xcb.h
@RobLoach you merged my last pull request so I'm taking that as approval to make similar changes to the other backends as appropriate.  I've done so to all except rawfb since that's kind of special/unfinished.
As I said before, I'm unable to easily test the Windows backends but they all use the same input method so if one works they should all work.
In the process of going through everything I found a couple issues I hope someone else can verify:
* glfw_gl4 demo crashes, something to do with the shaders, I didn't dig into it
* SFML Makefiles fail on linux, removing the "-s" suffixes on the libraries fixes it for me
* All SFML backends have a weird input bug
> Add NumPad Enter to other backends

- demo/glfw_opengl2/main.c
- demo/glfw_opengl2/nuklear_glfw_gl2.h
- demo/glfw_opengl3/main.c
- demo/glfw_opengl3/nuklear_glfw_gl3.h
- demo/glfw_opengl4/main.c
- demo/glfw_opengl4/nuklear_glfw_gl4.h
- demo/glfw_vulkan/main.c
- demo/glfw_vulkan/nuklear_glfw_vulkan.h
I was the [author](https://github.com/vurtun/nuklear/pull/765) for the [NK_KEYSTATE_BASED_INPUT](https://github.com/Immediate-Mode-UI/Nuklear/commit/69a2d50c9b7c4fd60e40db67cf3f8bc1d5e474d1) fix for the fix for the too-fast repeat behavior on glfw backends.
I was never really happy with it as, while it fixed repeat behavior for everyone else, it broke it for glfw.  If I had been less focused on Nuklear and more on GLFW (which I had never used before and still have almost 0 experience with) I would have realized that this is not a Nuklear problem and should not be handled by Nuklear proper but by the backend authors.
If I had paid attention I would have noticed we already handle the same problem with text input: we use the char callback and buffer the results to send all at once between …
> Fix glfw repeat behavior

- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sdl_renderer/nuklear_sdl_renderer.h
- demo/sdl_vulkan/nuklear_sdl_vulkan.h
Can't believe I never noticed this issue before.
Pretty self explanatory: use SDL_GetModState() to get whether either control is down and use that instead of the key state array.
> Add support for right control to sdl backends

- clib.json
- nuklear.h
- src/CHANGELOG
- src/nuklear_knob.c
- src/nuklear_panel.c
What it says on the tin.  Scrolling with the mouse hovering over a knob is supposed to just adjust the knob but it adjusts the knob and scrolls the parent window if possible so you get one change and then you're off it.
I looked at how nk_panel_end() handles it (eliminating some code while I was looking) but that would require more extensive changes and just setting the mouse delta.y to 0 works perfectly fine.
> Fix knob scrolling and remove some dead code

- clib.json
- nuklear.h
- src/CHANGELOG
- src/nuklear_input.c
compiler complains about unitialized data in `glyph` . 
Not sure if I should have changed CHANGELOG / clib.json
> fix: unintialized data in glyph

- clib.json
- demo/glfw_opengl3/Makefile
- demo/glfw_opengl3/main.c
- nuklear.h
- src/CHANGELOG
- src/HEADER.md
- src/nuklear_edit.c
- src/nuklear_text_editor.c
This does a few things.
1. It fixes the behavior of CTRL + LEFT/RIGHT to be both more standard and configurable.  By default it now jumps to the beginning of words with whitespace being the separator, roughly in line with other text editors.  Secondly the user can define NK_IS_WORD_BOUNDARY(c), a function style macro that takes a nk_rune aka nk_uint and returns true/1 if that character should be treated as a boundary, false otherwise.  Of course I did all this before I realized/remembered that nk_text_editor.c is adapted from stb_textedit.h 1.8 in 2016. Since then user configurable word boundaries was added as well as several other fixes up through current 1.14.  Sometime someone should review those changes and apply any we need or could benefit from.
2. It fixes mouse scrolling.  Like …
> Fix text input behavior

- demo/rawfb/sdl/main.c
- demo/sdl_opengl2/nuklear_sdl_gl2.h
- demo/sdl_opengl3/nuklear_sdl_gl3.h
- demo/sdl_opengles2/nuklear_sdl_gles2.h
- demo/sdl_renderer/nuklear_sdl_renderer.h
- demo/sdl_vulkan/nuklear_sdl_vulkan.h
- demo/sdl_vulkan/src/nuklear_sdl_vulkan.in.h
Using the precise scroll wheel infos makes the demos (and apps) feel much more smoothly, source looks nicer additionaly.
Especially using touchpad gestures.
> fix: use precise mouse wheel info in demos
